/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_linglong_ndkthread_NdkTool */

#ifndef _Included_com_linglong_ndkthread_NdkTool
#define _Included_com_linglong_ndkthread_NdkTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_linglong_ndkthread_NdkTool
 * Method:    testCallBack
 * Signature: (Lcom/linglong/ndkthread/NdkData;Lcom/linglong/ndkthread/NdkCallBack;)V
 */
JNIEXPORT void JNICALL Java_com_linglong_ndkthread_NdkTool_testCallBack
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
